### ISSUE TITLE
This issue is for image hosting only.

### ISSUE THREAD

**Issue by markkod** [markkod/kaggle-football-prediction#3]
![balanced](https://user-images.githubusercontent.com/25458629/84670859-5275d880-af2f-11ea-99af-49721f8f1fe7.png)
![betting_constant_away](https://user-images.githubusercontent.com/25458629/84670862-53a70580-af2f-11ea-8063-fa9c6fc64789.png)
![betting_constant_draw](https://user-images.githubusercontent.com/25458629/84670864-543f9c00-af2f-11ea-9f91-f22e1e709a90.png)
![betting_constant_home](https://user-images.githubusercontent.com/25458629/84670865-54d83280-af2f-11ea-806d-b313e18c1aa0.png)
![betting_neural_network](https://user-images.githubusercontent.com/25458629/84670866-54d83280-af2f-11ea-837d-eddba27460b0.png)
![betting_random_forest](https://user-images.githubusercontent.com/25458629/84670867-5570c900-af2f-11ea-89fa-a7a12df526d1.png)
<img width="582" alt="confusion" src="https://user-images.githubusercontent.com/25458629/84670868-5570c900-af2f-11ea-89aa-6c52b1d03c75.png">
![imbalanced](https://user-images.githubusercontent.com/25458629/84670870-56095f80-af2f-11ea-823b-1091539b9e89.png)

**Comment by rosulg** [comment]
![confusion_matrix_random_forest](https://user-images.githubusercontent.com/25638055/84686732-2e24f680-af45-11ea-93de-4aaff60d37d3.png)
![random_forest_decision_tree](https://user-images.githubusercontent.com/25638055/84686739-30875080-af45-11ea-810f-5a4497f93e0c.png)

**Comment by markkod** [comment]
![betting_best_odds](https://user-images.githubusercontent.com/25458629/84688470-0f742f00-af48-11ea-87a0-d6e5f6958f58.png)
